site_name: Vidst
site_description: AI-powered video understanding and analysis system - POC
site_author: admarble
site_url: https://admarble.github.io/Vidst
repo_name: admarble/Vidst
repo_url: https://github.com/admarble/Vidst
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 Your Organization
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.top
  - search.suggest
  - search.highlight
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
- admonition
- codehilite
- footnotes
- meta
- toc:
    permalink: true
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
nav:
- Home: index.md
- Getting Started:
  - Installation: getting_started/installation.md
  - Setup: getting_started/setup.md
  - Quick Start: getting_started/quickstart.md
- Components:
  - Status Dashboard: components/status_dashboard.md
  - Scene Detection: components/scene_detection.md
  - Audio Transcription: components/audio_transcription.md
  - OCR: components/ocr.md
- Architecture:
  - System Overview: architecture/system_overview.md
- Guides:
  - Video Processing: guides/video-processing.md
  - Models:
    - GPT-4V: guides/models/gpt4v.md
- API Reference:
  - Overview: api/index.md
  - Models:
    - GPT-4V: api/ai/models/gpt4v.md
- Troubleshooting:
  - Common Issues: troubleshooting/common-issues.md
- Reference:
  - Package Compatibility: package_compatibility.md
  - Test Fixes: test_fixes.md
plugins:
- search
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/admarble/Vidst
  version:
    provider: mike
